### ISSUE TITLE
set up a test database to test database queries

### ISSUE THREAD

**Issue by jdy3** [fac18/week6-week7-FHIN-got-db-auth#17]

**Comment by samjam48** [comment]
1. Make a new database locally and put the url into your config.env file

2. Add a clause to your db_connection.js to make sure you set the connnection url to teh test database.

```
let DB_URL = process.env.DB_URL;

if (process.env.NODE_ENV === "test") {
  DB_URL = process.env.TEST_DB_URL;
}
```

3. Create a database.test.js file and try and write a test for each query.
(see workshop https://github.com/foundersandcoders/ws-database-testing/)
