### ISSUE TITLE
Great concept

### ISSUE THREAD

**Issue by marialani** [fac18/week6-week7-FHIN-got-db-auth#42]
This was a great idea and from your user stories I can see what you were intending the finished product to look like, you've done very well so far and I look forward to seeing your final version. Congrats guys!

**Comment by redahaq** [comment]
@marialani Thank you that's so lovely and heartening to hear at this stage! 😂

**Comment by marialani** [comment]
![](https://media.giphy.com/media/fmd46gcrNQJePMU6xa/giphy.gif)
