### ISSUE TITLE
cookie trouble 🍏 🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🍈 🍒

### ISSUE THREAD

**Issue by bethanyios** [fac18/week6-week7-FHIN-got-db-auth#87]
Found a weird message about cookies - the encrypted password value is appearing along with my name but not within the same section. 
The message mentions something about samesite because of an external resource with fontmemes. 

![Screen Shot 2019-12-13 at 10 58 29](https://user-images.githubusercontent.com/36175966/70796301-d0e39900-1d99-11ea-8f3c-297c4bdcf2a4.png)

I looked into the message and found the documentation on how to avoid this https://web.dev/samesite-cookies-explained/

**Comment by redahaq** [comment]
Thanks.. this is a soon-to-be-implemented Google thing. It happens with font-awesome icons etc as well and I'd been trying to figure out where the fix would go before we learnt about cookies! This is so helpful :)

We used SameSite: Strict; to fix it :)
